SUPABASE_URL = "https://vbnkwkblpidfiphuuaic.supabase.co"
SUPABASE_ANON_KEY = "sb_publishable_01GxUrdre4SRgs_hFQrvAg_FTk8Vc7l"
SUPABASE_REDIRECT_URL = "https://rollsyncpro-bjxd6fh9habffhs8utbbla.streamlit.app/"
